[platformio]
default_envs = esp32s3

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
monitor_filters = send_on_enter

build_flags =
    -DAPP_MODE_DEBUG
    -DFIXTURE_DEFAULT

[env:esp32s3]
board = esp32-s3-devkitc-1
upload_protocol = esptool
monitor_rts = 0
monitor_dtr = 0
build_flags =
    ${env.build_flags}
    -DFW_BOARD_NAME=\"Unites32\"
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1	
    -DBOARD_ESP32S3

[env:esp32wroom32]
board = denky32
build_flags =
    ${env.build_flags}
    -DFW_BOARD_NAME=\"Denky32\"
    -DBOARD_ESP32WROOM32
	
[env:esp32dev_16mb]
board = esp32dev
board_upload.flash_size = 16MB
board_build.partitions = partitions_16mb_ota.csv
build_flags =
    ${env.build_flags}
    -DFW_BOARD_NAME=\"Bin-Der32\"
    -DBOARD_ESP32DEV_16MB